function GetOverTrees() {

move();
turnLeft();
move();
move();
move();
turnRight();
move();
turnRight();
move();
move();
move();
turnLeft();
move();
move();
turnLeft();
move();
move();
turnRight();
move();
turnRight();
move();
move();
turnLeft();
move();
move();
move();
turnLeft();
move();
move();
move();
move();
turnRight();
move();
turnRight();
move();
move();
move();
move();
turnLeft();
move();
move();
turnLeft();
move();
move();
move();
turnRight();
move();
turnRight();
move();
move();
move();
turnLeft();
move();
move();


}








function turnRight() {

turnLeft();
turnLeft();
turnLeft();

}
